make linker scripts more dynamic

diff --git a/.cargo/linker/linux/aarch64/zigcc-musl b/.cargo/linker/linux/aarch64/zigcc-musl
--- a/.cargo/linker/linux/aarch64/zigcc-musl
+++ b/.cargo/linker/linux/aarch64/zigcc-musl
@@ -1,2 +1,8 @@
 #!/bin/sh
-/opt/homebrew/bin/zig cc -static -target aarch64-linux-musl $@
+
+ZIG_PATH=$(which zig)
+if [ -z "$ZIG_PATH" ]; then
+    echo "Zig compiler not found in PATH"
+    exit 1
+fi
+"$ZIG_PATH" cc -static -target aarch64-linux-musl "$@"
diff --git a/.cargo/linker/linux/x86_64/zigcc-musl b/.cargo/linker/linux/x86_64/zigcc-musl
--- a/.cargo/linker/linux/x86_64/zigcc-musl
+++ b/.cargo/linker/linux/x86_64/zigcc-musl
@@ -1,2 +1,13 @@
 #!/bin/sh
-/opt/homebrew/bin/zig cc -static -target x86_64-linux-musl $@
+
+TARGET_ARCH="x86_64"
+TARGET_OS="linux-musl"
+
+TARGET_PLATFORM="${TARGET_ARCH}-${TARGET_OS}"
+ZIG_PATH=$(which zig)
+
+if [ -z "$ZIG_PATH" ]; then
+    echo "Zig compiler not found in PATH"
+    exit 1
+fi
+"$ZIG_PATH" cc -static -target "$TARGET_PLATFORM" "$@"
